//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoLegal.Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int IDWeather { get; set; }
        public decimal Temperature { get; set; }
        public decimal Humidity { get; set; }
        public System.DateTime RequestDate { get; set; }
    }
}
